apiVersion: apps/v1
kind: Deployment
metadata:
  name: upg-loadme-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: upg-loadme
  template:
    metadata:
      name: upg-loadme-deployment
      labels:
        app: upg-loadme
    spec:
      containers:
      - name: upg-loadme
        image: 788051511621.dkr.ecr.us-east-1.amazonaws.com/capstone-mitali:latest
      tolerations:
      - key: "app"
        operator: "Equal"
        value: "upg-loadme"
        effect: "NoSchedule"   
---
apiVersion: v1
kind: Service
metadata:
  name: upg-loadme-deployment
spec:
  type: LoadBalancer
  selector:
    app: upg-loadme
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8081
     
